name: Playwright Tests

# Trigger the workflow on push to specific branches
on:
  push:
    branches:
      - main        # Change to your deployment branch if different (e.g. 'production')
  # Alternatively, you can trigger on `deployment` events after deploying.
  deployment_status:
    types: [success]

jobs:
  # Job 1: Build and run Playwright tests
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build the Docker image
        run: |
          docker build -t playwright-test .

      - name: Run Playwright Tests
        run: |
          docker run --rm playwright-test
