name: Playwright Tests

# Trigger the workflow on push to specific branches
on:
  push:
    branches:
      - master        

  workflow_run:
    workflows: ["Deploy Application"]  # The workflow name from the first file
    types:
      - completed  # Trigger when the deployment workflow completes

jobs:
  # Job 1: Build and run Playwright tests
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build the Docker image
        run: |
          docker build -t playwright-test .

      - name: Run Playwright Tests
        run: |
          docker run --rm playwright-test
